### ISSUE TITLE
NLag ZIP Not Properly Formatted For R2ModMan

### ISSUE THREAD

**Issue by ultimaplayer12** [DrMeepso/NLag#2]
I know that R2ModMan is not the primary mod manager for WEBFISHING, but as it is supported and my preference I think this should be fixed.

The issue seems to be that the ZIP file does not contain a folder that contains the files, instead it just directly contains the files. If nested into a folder, then it is able to be installed with R2ModMan. I would suggest fixing this ASAP, thank you for your work!

**Comment by DrMeepso** [comment]
done!
